name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  id-token: write
  contents: read

env:
  TF_WORKSPACE: ${GITHUB_REF:-test}

jobs:
  test:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: Test

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.AWS_ROLE_ARN }}
        role-session-name: TerraformTest
        aws-region: ${{ vars.AWS_DEFAULT_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3.1.2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Test
      run: |
        terraform test -compact-warnings | tee >(sed $'s/\033[[][^A-Za-z]*m//g' > tf_output.log)
        grep -v 'Warnings:' tf_output.log | \
        grep -v 'Applied changes may be incomplete' | \
        grep -v 'Resource targeting is in effect' | \
        grep -v 'To see the full warning notes' | \
        awk NF >> $GITHUB_STEP_SUMMARY
